== Declarative Deployment

For this example you can use any Kubernetes installation you have access to.
See the link:../../INSTALL.adoc[INSTALL] documentation for some options you have.

Let's now look, how we can get out https://github.com/k8spatterns/random-generator[random-generator] application from version 1 to version 2 with different update strategies.

First, install the application in version 1 by using the given deployment descriptor

[source, bash]
----
kubectl create -f rolling-update.yml
----

This will deploy 3 replicas of the `random-generator` and configures a `RollingUpdate` update strategy (which would be also the default).

In order to be able to access our application, lets create a Service and Ingress object, too:

[source, bash]
----
kubectl create -f service-and-ingress.yml
----

The Service is of type `LoadBalancer`, which will create an Azure Load Balancer with a public IP so you can acces your service. Watch the service creation until the *EXTERNAL-IP* value is populated.

[source, bash]
----
kubectl get svc random-generator -w
----

Let's start now in a dedicated terminal window a loop which constantly accesses our Service.

[source, bash]
----
PUBLICIP="$(kubectl get svc -o jsonpath={$.status.loadBalancer.ingress[0].ip} random-generator)"
while true; do
  curl -s http://"${PUBLICIP}":8080/info | jq '.version,.id'
  echo ===========================
  sleep 1
done
----

Alternatively, if you are on a node in the cluster, you can also use the script `call_random_generator.sh` which does the same but via the Service's node port and can be used on e.g. the Kubernetes playgrounds footnote:[You can open multiple terminals on Katakoda with the '+' sign beside the terminal tabs].

Now it's time to update to version 2.0.
As mentioned in the book, you can do it in several ways.
Here we are using the easiest one and call `kubectl set image`:

[source, bash]
----
kubectl set image deployment random-generator random-generator=k8spatterns/random-generator:2.0
----

After you started the deployment you can do several things to monitor the update:

* Watch the terminal with the query loop we started. Do you see the change from version 1 to version 2 ? Are there any errors reported by curl ?
* Use `kubectl get pods -w` to watch how the Pods are coming down and up
* Use `kubectl rollout status deployment random-generator` to see the status of the rollout.

When the update has finished, let's have some fun:

* Rollback the deployment with `kubectl rollout undo deploy/random-generator`
* Check the update history `kubectl rollout history deploy/random-generator`


Finally let's switch the update strategy to `Recreate`:

[source, bash]
----
kubectl replace -f recreate.yml

# Update to version 2.0 (or change to 1.0 when you have 2.0 running)
kubectl set image deployment random-generator random-generator=k8spatterns/random-generator:2.0
----

Can you spot the difference when doing the update, also with respect to the downtime ?

=== More Information

* https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/[Rolling Update]
* https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[Deployments]
* http://kubernetes.io/docs/user-guide/deploying-applications/[Deploying Applications]
* http://martinfowler.com/bliki/BlueGreenDeployment.html[Blue-Green Deployment]
* https://martinfowler.com/bliki/CanaryRelease.html[Canary Release]
* https://www.openshift.com/promotions/devops-with-openshift.html[DevOps with OpenShift]
