== Predictable Demands

ifndef::skipInstall[]
For this example we recommend to use a Azure Kubernetes Service (AKS) cluster installation described link:https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough[here].
endif::skipInstall[]

To access the PersistentVolume used in this demo, let's create an Azure Files Storage Class with the name "azurefile" that we later then use a PersistentVolume mounted into the Pod:

[source, bash]
----
kubectl apply -f azure-file-sc.yaml
----

To allow the Azure platform to create the required storage resources, let's create a new ClusterRole and ClusterRoleBinding:

[source, bash]
----
kubectl apply -f azure-pvc-roles.yaml
----

For this (and many other demos) we are using a simple https://github.com/k8spatterns/random-generator[random number service], which is a simple REST service exposing a random number and can be found also in the image `k8spatterns/random-generator:1.0` on Docker Hub

=== Hard requirements

We will set up this image that it will write a log file in a PV and get some configuration data from a ConfigMap.

Now lets try to create the Pod

[source, bash]
----
kubectl create -f https://k8spatterns.io/PredictableDemands/pod.yml
----

When we verify this with we immediately see, that pod doesn't start:

[source, bash]
----
kubectl get pods

NAME               READY   STATUS    RESTARTS   AGE
random-generator   0/1     Pending   0          3s
----

The first reason is, that the PVC is missing as you can easily see when describing the pod:

[source, bash]
----
kubectl describe pod random-generator

...
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  44s (x2 over 44s)  default-scheduler  persistentvolumeclaim "random-generator-log" not found
----

Let's now create the PersistentVolumeClaim:

[source, bash]
----
kubectl create -f azure-pvc.yml
----

When we create the PV and PVC we are already one step further:

[source, bash]
----
kubectl describe pod random-generator

...
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  32s (x5 over 7m44s)  default-scheduler  persistentvolumeclaim "random-generator-log" not found
  Warning  FailedScheduling  15s (x6 over 15s)    default-scheduler  pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         15s                  default-scheduler  Successfully assigned default/random-generator to minikube
  Normal   Pulled            3s (x3 over 14s)     kubelet, minikube  Container image "k8spatterns/random-generator:1.0" already present on machine
  Warning  Failed            3s (x3 over 14s)     kubelet, minikube  Error: configmap "random-generator-config" not found
----

The PVC could be bound, but now the ConfigMap is missing.

Let's add this last missing piece:

[source, bash]
----
kubectl create -f https://k8spatterns.io/PredictableDemands/configmap.yml
----

and the pod will be finally up:

[source, bash]
----
kubectl get pods
NAME               READY   STATUS    RESTARTS   AGE
random-generator   1/1     Running   0          3s
----

We can easily check this by sending an HTTP request.
As we haven't installed a Service, lets poke a hole with a port-forward into the cluster and use curl to check the output:

[source, bash]
----
# Port forward to Pod
kubectl port-forward pod/random-generator 8080:8080 &

# Send a request to our service
curl -s http://localhost:8080 | jq .

{
  "random": 79003229,
  "pattern": "Predictable Demands",
  "id": "d88cc0e5-c7f2-4e98-8073-ed76151b5218",
  "version": "1.0"
}
----

Check whether the log has been written to the Azure Files location. To do this, open the link:https://portal.azure.com[Azure portal] and find the management Resource Group for the AKS cluster, which will be a Resource Group with a name format of MC_<AKS Resource Group Name>_<AKS Cluster Name>_<Azure Region>.

. Within that Resource Group, locate the storage account (there will only be one unless the cluster has been used for other tasks)
. Open the storage account and click into the *Files* section
. There will be a file share with a name starting with *"kubernetes-dynamic-pvc"* followed by a random GUID
. Open the file share and you will see a file named *random.log*
. Click on the file and download it to view the contents

[source, bash]
----
17:58:54.303,521d0872-c60d-4049-9ba5-7aff095abd17,52302,-551447824
----

Now that our hard requirements (ConfigMap, PVC) are fulfilled our the application runs smoothly.

If you are done, it's a good idea to cleanup:
[source, bash]
----
# Killt the 'kubectl port-forward' first
kill %1

# Delete the plain pod
kubectl delete pod/random-generator

# Delete PVC
kubectl delete -f azure-pvc.yml
----

=== Resource limits

Let's create now a real Deployment with resource limits

[source, bash]
----
kubectl create -f https://k8spatterns.io/PredictableDemands/deployment.yml
----

This will use 200M as upper limit for our application.
Since we are using Java 11 as JVM for our Java application, the JVM respects this boundary
and allocates only a fraction of this as heap.
You can easily check this with

[source, bash]
----
# The 'pod' alias is explained in INSTALL.adoc
kubectl logs $(pod random-generator) | grep "=== "

i.k.examples.RandomGeneratorApplication  : === Max Heap Memory:  96 MB
i.k.examples.RandomGeneratorApplication  : === Used Heap Memory: 37 MB
i.k.examples.RandomGeneratorApplication  : === Free Memory:      13 MB
i.k.examples.RandomGeneratorApplication  : === Processors:       1
----

Let's now try to change our limits and requests with smaller and larger values.


[source, bash]
----
patch=$(cat <<EOT
[
  {
    "op": "replace",
    "path": "/spec/template/spec/containers/0/resources/requests/memory",
    "value": "30Mi"
  },
  {
    "op": "replace",
    "path": "/spec/template/spec/containers/0/resources/limits/memory",
    "value": "30Mi"
  }
]
EOT
)
kubectl patch deploy random-generator --type=json -p $patch
----

If you check your Pods now with `kubectl get pods` and `kubectl describe`, do you see what you expect ?
Also don't forget the check the logs, too !

=== More Information

* https://github.com/k8spatterns/examples/tree/master/foundational/PredictableDemands[Predictable Demands example]
* https://attractivechaos.github.io/plb/[Programming language benchmarks]
* http://kubernetes.io/docs/user-guide/configmap/[Using ConfigMap]
* http://kubernetes.io/docs/user-guide/config-best-practices/[Best Practices for Configuration]
* http://kubernetes.io/docs/user-guide/persistent-volumes/[Persistent Volumes]
* http://kubernetes.io/docs/admin/resourcequota/[Resource Quotas]
* http://kubernetes.io/docs/admin/resourcequota/walkthrough/[Applying ResourceQuotas and Limits]
* https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-resource-requests-and-limits/[Kubernetes best practices: Resource requests and limits]
* https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-qos.md[Resource Quality of Service in Kubernetes]
* http://kubernetes.io/docs/admin/limitrange/[Setting Pod CPU and Memory Limits]
